
version: '3'
services:
  markov:
    build: .
    ports:
     - "8080:8080"
    environment:
     - MARKOV_REDISADDR="redis:6379"
    depends_on:
     - redis
    links:
     - redis
  redis:
    image: redis:latest